import { Button, VerticalBox, GridBox, LineEdit } from "std-widgets.slint";
import { Button, VerticalBox, GridBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    background: #004D1A;

    in property <string> results;
    callback divide_income(string);

   GridBox {
        padding: 50px;
        spacing: 24px;
        
        Row{    
            Text {
                text: "Enter Total Income";
                color: red;
                horizontal-alignment: center;
                font-size: 20px;
                font-weight: 800;
            }
        }
        Row{   
            income := LineEdit {
                placeholder-text: "Enter Total Income";
                horizontal-alignment: center;
                font-size: 30px; 
                height: 25px;
            }
        }
        Row{
            Button {
                text: "Calculate";
                primary: true;
                height: 25px;   
                clicked => {divide_income(income.text)}
            }

        }
        Row{
            VerticalBox {
                Rectangle {
                    height: 140px;   
                    background: gray;
                    Text {
                        color: black;
                        font-size: 15px ;
                        font-weight: 300 ;
                        text: root.results;

                    }
                }
                

            }

        }
   }
}

