import { Button, VerticalBox, GridBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    background: black;
   GridBox {
        padding: 50px;
        spacing: 24px;
        
        Row{    
            Text {
                text: "Enter Total Income";
                color: blue;
                horizontal-alignment: center;
                font-size: 20px;
                font-weight: 800;
            }
        }
        Row{   
            LineEdit {
                placeholder-text: "Enter Total Income";
                horizontal-alignment: center;
                font-size: 24px; 
                height: 25px;   

            }

        }
        Row{
            Button {
                text: "Calculate";
                primary: true;
                height: 25px;   


            }

        }
   }
}
